# Alternative GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  opengl_study_config = debug

else ifeq ($(config),release)
  opengl_study_config = release

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := opengl-study

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

opengl-study:
ifneq (,$(opengl_study_config))
	@echo "==== Building opengl-study ($(opengl_study_config)) ===="
	@${MAKE} --no-print-directory -C . -f opengl-study.make config=$(opengl_study_config)
endif

clean:
	@${MAKE} --no-print-directory -C . -f opengl-study.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   opengl-study"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"